"""create initial tables

Revision ID: c42ee79707ed
Revises: 
Create Date: 2026-05-31 14:42:15.982025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42ee79707ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('site', 'meta_ads', 'whatsapp', 'portal', 'indicacao', 'manual', name='leadsource', native_enum=False, length=40), nullable=False),
    sa.Column('campaign', sa.String(length=200), nullable=True),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('utm_medium', sa.String(length=200), nullable=True),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('nova', 'contactada', 'qualificada', 'encaminhada', name='leadstatus', native_enum=False, length=40), nullable=False),
    sa.Column('responsible_area', sa.Enum('inside_sales', 'buyer_advisory', 'sell_advisor_mediacao', 'credito_habitacao', 'spv_investimentos', name='responsiblearea', native_enum=False, length=40), nullable=False),
    sa.Column('interest', sa.Enum('comprar_imovel', 'vender_imovel', 'credito_habitacao', 'investimento_spv', name='leadinterest', native_enum=False, length=40), nullable=True),
    sa.Column('sla_status', sa.Enum('dentro_sla', 'fora_sla', name='slastatus', native_enum=False, length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('routed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('chamada', 'whatsapp', 'email', name='interactiontype', native_enum=False, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_lead_id'), 'interactions', ['lead_id'], unique=False)
    op.create_table('lead_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('lead_criada', 'primeiro_contacto', 'qualificacao', 'encaminhamento', name='historyactiontype', native_enum=False, length=40), nullable=False),
    sa.Column('previous_status', sa.Enum('nova', 'contactada', 'qualificada', 'encaminhada', name='leadstatus', native_enum=False, length=40), nullable=True),
    sa.Column('new_status', sa.Enum('nova', 'contactada', 'qualificada', 'encaminhada', name='leadstatus', native_enum=False, length=40), nullable=True),
    sa.Column('previous_area', sa.Enum('inside_sales', 'buyer_advisory', 'sell_advisor_mediacao', 'credito_habitacao', 'spv_investimentos', name='responsiblearea', native_enum=False, length=40), nullable=True),
    sa.Column('new_area', sa.Enum('inside_sales', 'buyer_advisory', 'sell_advisor_mediacao', 'credito_habitacao', 'spv_investimentos', name='responsiblearea', native_enum=False, length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_history_lead_id'), 'lead_history', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_history_lead_id'), table_name='lead_history')
    op.drop_table('lead_history')
    op.drop_index(op.f('ix_interactions_lead_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('contacts')
    # ### end Alembic commands ###
